# Secret for sensitive environment variables
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  JWT_SECRET: and0X3NlY3JldA==
---

# Deployment for the Node.js application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: gateway-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000  # Application's internal port
        env:
          - name: AUTH_PORT
            value: "4000"
          - name: GATEWAY_PORT
            value: "3000"
          - name: AUTHENTICATOR_URL
            value: "http://authapp-service:4000"
          - name: REDIS_HOST
            value: "redis"
          - name: REDIS_PORT
            value: "6379"
          - name: DB_USER
            value: "luckyspin_data_admin"
          - name: DB_HOST
            value: "postgres"
          - name: DB_NAME
            value: "luckyspin_data"
          - name: DB_PORT
            value: "5432"
          - name: DB_PASS
            value: "luckyspin_data_pwd"
          - name: ALLOWED_ORIGINS
            value: "https://example.com,http://localhost:5173" #For vite app and tests, append the list
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET
        volumeMounts:
          - mountPath: /app/config
            name: config-volume
      volumes:
        - name: config-volume
          emptyDir: {}

---

# Service with NodePort to expose the application
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 3000             # Internal Cluster IP service port
      targetPort: 3000       # Application container port
      nodePort: 31000        # NodePort for external access (30000-32767 range)
